# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c3caf0b21aad2d1c488bb454fb09f3a97c4a707823bf10c9f6258da79f4774f10be80f056d8c5ac27a7a712040d157c2c2b8020c949a5fb22f5ac94357ebad1
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  AWS_REGION: us-west-2

test:
  secret_key_base: 6eaf0684adfd33c4b2a0b2670bb66f414b7f57c3d7140ed5d8a40266c3cafc71bbc617407e4c40a24b484e41d9fa62bfedd919d39ee72e0531fe8a440fe81b9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
